### ISSUE TITLE
vm_os_checker.py error

### ISSUE THREAD

**Issue by Tecnico1931** [killahquam/OSXScripts#2]
Getting this error:

Traceback (most recent call last):
  File "./vm_os_checker.py", line 104, in <module>
    results.append(found_para())
  File "./vm_os_checker.py", line 92, in found_para
    t = m[0].translate(None,",")
IndexError: list index out of range

**Comment by killahquam** [comment]
What OS and Python version are you running, I just ran the code without issue on 10.11.2 via CLI python 2.7.10

**Comment by Tecnico1931** [comment]
Same OS and version  I will test it this week and if I get more errors I will post them on here .

**Comment by austingecko** [comment]
Same exact problem for me as well. Originally trying to implement in Casper as per your great blog but wasn't getting any hits on the SmartGroup. Then ran the python script directly on my Mac OS X 10.11.6 and got the error below. 

Traceback (most recent call last):
File "./vm_os_checker.py", line 104, in 
results.append(found_para())
File "./vm_os_checker.py", line 92, in found_para
t = m[0].translate(None,",")
IndexError: list index out of range

**Comment by killahquam** [comment]
Will look at it this weekend. sadly my current org doesn't use Casper so I
can only check the script

**Comment by austingecko** [comment]
Thanks for the prompt response. My environment has both Parallels and VMWare which I confirmed are being found by enabling the print files commands.

**Comment by killahquam** [comment]
What OS are you running the script on ? I just tested it on Sierra and it worked fine without issues via sudo.
<img width="186" alt="screen shot 2016-09-25 at 2 55 30 pm" src="https://cloud.githubusercontent.com/assets/3904230/18818517/25abde0a-8330-11e6-9e33-b4daa9f0a553.png">

I will check on El Capitan to see if I get the same results

**Comment by austingecko** [comment]
I'm on El Cap 10.11.6 running Python 2.7.10. I run from command line using sudo python <script.py> and get the error. Do I need to add command line arguments to the script when running manually?

**Comment by austingecko** [comment]
When I comment out line 15 & 16 and replace with parallels_files = "" then the script runs. Looks like there is something being returned when looking for the Parallels files is causing the issue.  Do you think it might be erroring because my VMs have spaces in the names, i.e. "Windows 10.pvm" and "OS X Dev.pvm".

**Comment by killahquam** [comment]
It shouldn't since it's looking for *.pvm

**Comment by austingecko** [comment]
Here's what is returned when I print parallels_files (4 results match):

['/Users/Admin/Documents/Parallels/Copy of Win 7 Ultimate.pvm/VmInfo.pvi', '/Users/Admin/Documents/Parallels/OS X Dev.pvm/VmInfo.pvi', '/Users/Admin/Documents/Parallels/Win 7 Clean.pvm/VmInfo.pvi', '/Users/Admin/Documents/Parallels/Windows 10.pvm/VmInfo.pvi']

**Comment by killahquam** [comment]
ok, looks like parallels files have changed to .pvi

**Comment by austingecko** [comment]
Inside the .pvm package which is the name of the Parallels vm is the VmInfo.pvi file.
